import {createFileRoute} from '@tanstack/react-router';
import {useState,type FormEvent} from 'react';
import {ScrollScrub} from '@/components/scroll-scrub/scroll-scrub';
import {scrollScrubScenes,scrollScrubTheme} from '@/scroll-scrub-scenes';
import {submitEnquiry} from '@/lib/api/enquiry.functions';
export const Route=createFileRoute('/')({component:Home});
const capabilities=[['Outpatient & queues','Coordinate registration, arrivals and daily flow.'],['Beds & admissions','See availability, admissions and turnover.'],['Billing & collections','Keep charges, invoices and payments together.'],['Finance & profitability','Understand revenue, expenses, profit and loss.'],['Pharmacy & inventory','Connect stock, purchasing, sales and margins.'],['Maintenance & tickets','Assign issues and follow work to completion.'],['People & departments','Coordinate teams, responsibilities and handovers.'],['Procurement & stores','Track requests, suppliers and stock movement.']];
const lessons=[{title:'Getting started with Dhanjiva',description:'Find your way around the tool and set up your workspace.',topic:'Getting started'}, {title:'Managing daily operations',description:'Learn the flow for queues, beds, teams and maintenance.',topic:'Manage'}, {title:'Reading your hospital financials',description:'Understand billing, expenses, margins and profit or loss.',topic:'Analyse'}, {title:'Working with pharmacy and inventory',description:'Follow purchases, stock movement, sales and expiry tracking.',topic:'Manage'}];
const faqs=[['Is Dhanjiva one tool?','Yes. Dhanjiva is one hospital management tool. Operations, finance, pharmacy and other department workflows are capabilities within that tool.'],['What are Modules?','Modules are tutorial videos that teach you how to use Dhanjiva. They are learning content, not separate tools or products.'],['How do I get Dhanjiva?','Send an access request below to discuss your hospital’s setup and purchase details. Online checkout is not currently connected.'],['Does it cover medical treatment?','Dhanjiva focuses on hospital management and business operations. It is not a diagnosis or treatment tool.']];
function Home(){
 const [menu,setMenu]=useState(false),[mode,setMode]=useState<'Manage'|'Analyse'>('Manage'),[lesson,setLesson]=useState(0);

 return <>
 <a className="skip-link" href="#tools">Skip to tool</a>
 <header className="site-header"><a className="brand" href="#overview" aria-label="Dhanjiva home"><img src="/assets/dhanjiva-logo.jpg" alt="" width="42" height="42"/><span>Dhanjiva</span></a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}<span aria-hidden="true">{menu?'×':'☰'}</span></button><nav id="main-nav" className={menu?'main-nav open':'main-nav'} aria-label="Main navigation">{[['Tools','#tools'],['Modules','#modules'],['Help','#help']].map(([label,href])=><a className={label==='Tools'?'tools-nav':''} key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}<a className="nav-demo" href="#tools" onClick={()=>setMenu(false)}>Get Dhanjiva <span aria-hidden="true">↗</span></a></nav></header>
 <main><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme} className="dhanjiva-journey corridor-journey connected-journey"/>
 <section id="tools" className="single-tool-section" aria-labelledby="tools-title"><div className="section-wrap"><div className="product-heading"><p className="eyebrow">THE DHANJIVA TOOL</p><h2 id="tools-title">One tool.<br/><span>Your whole hospital.</span></h2><p>Manage the everyday. Understand the bigger picture.</p></div><div className="product-showcase"><div className="product-identity"><img src="/assets/dhanjiva-logo.jpg" width="718" height="590" alt="Dhanjiva brand mark"/><div><h3>Dhanjiva</h3><p>Hospital management, connected.</p></div><span className="product-caption">One connected workspace</span></div><div className="product-offer"><h3>Everything works<br/>better together.</h3><p>One place to manage hospital operations and analyse performance across every department.</p><ul className="product-benefits"><li>Run daily hospital workflows</li><li>See revenue, costs and profitability</li><li>Keep departments working together</li></ul><a className="purchase-cta" href="#demo">Get Dhanjiva <span aria-hidden="true">↗</span></a><p className="purchase-note">Request access and purchase details for your hospital.</p><a className="learn-link" href="#modules">Explore learning modules <span aria-hidden="true">→</span></a></div></div>
 <div className="capability-header"><h3>All inside Dhanjiva.</h3><div className="mode-switch" role="group" aria-label="Explore tool capabilities">{(['Manage','Analyse'] as const).map(name=><button key={name} aria-pressed={mode===name} onClick={()=>setMode(name)}>{name}</button>)}</div></div><div className="capability-panel" aria-live="polite">{mode==='Manage'?<div className="capability-grid">{capabilities.map(([name,description],i)=><div className="capability-item" key={name}><img src={`/assets/icon-${i}.png`} width="38" height="38" alt="" loading="lazy"/><div><h4>{name}</h4><p>{description}</p></div></div>)}</div>:<div className="analysis-content"><h4>A clearer view of hospital performance.</h4><p>Bring departmental activity and financial results together to understand where money comes in, where it goes, and what needs attention.</p><ul><li>Revenue and collections</li><li>Expenses and operating costs</li><li>Profit and loss</li><li>Department performance</li><li>Pharmacy margins</li><li>Stock value and movement</li></ul></div>}</div></div></section>
 <section id="modules" className="learning-section" aria-labelledby="modules-title"><div className="section-wrap"><div className="learning-heading"><div><p className="eyebrow">LEARN DHANJIVA</p><h2 id="modules-title">Your tool.<br/>Step by step.</h2></div><p>Short video modules to help your team learn how to use Dhanjiva.</p></div><div className="learning-layout"><div className="lesson-stage"><div className="lesson-cover"><img src="/assets/learning.webp" width="1400" height="788" alt="A laptop and notebook ready for software training in a bright administration office" loading="lazy"/><div className="video-unavailable"><span className="video-symbol" aria-hidden="true">▷</span><span>Video coming soon</span></div></div><div className="lesson-caption" aria-live="polite"><span>{lessons[lesson].topic}</span><h3>{lessons[lesson].title}</h3><p>{lessons[lesson].description}</p></div></div><div className="lesson-list" role="group" aria-label="Learning modules"><p className="lesson-list-title">Video modules</p>{lessons.map((item,index)=><button key={item.title} aria-pressed={lesson===index} onClick={()=>setLesson(index)}><span className="lesson-number">{String(index+1).padStart(2,'0')}</span><span><strong>{item.title}</strong><small>Coming soon</small></span><span aria-hidden="true">▷</span></button>)}<p className="lesson-notice">Tutorial videos will appear here when they are available.</p></div></div></div></section>
 <section id="help" className="help-section section-wrap" aria-labelledby="help-title"><div className="help-heading"><h2 id="help-title">Ready for a clearer view?</h2><p>Bring your hospital together with Dhanjiva.</p></div><div className="help-layout"><div className="faq-list"><h3>A little clarity.</h3>{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><DemoForm/></div></section>
 </main><footer className="site-footer section-wrap"><a className="brand" href="#overview"><img src="/assets/dhanjiva-logo.jpg" alt="" width="42" height="42"/><span>Dhanjiva</span></a><p>One tool for the people running the hospital.</p><a href="#tools">Get Dhanjiva <span aria-hidden="true">↗</span></a><small>© 2026 Dhanjiva</small></footer></>;
}
function DemoForm(){
 const [pending,setPending]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false),[reference,setReference]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;const form=event.currentTarget, data=new FormData(form);setPending(true);setMessage('');try{const result=await submitEnquiry({data:{name:String(data.get('name')||''),email:String(data.get('email')||''),hospital:String(data.get('hospital')||''),interest:'Complete hospital',website:String(data.get('website')||''),consent:true}});setMessage(result.message);if(result.ok){setDone(true);setReference('reference' in result?result.reference||'':'');}}catch{setMessage('We could not save your request. Please check your connection and try again.');}finally{setPending(false);}}
 return <div id="demo" className="demo-panel">{done?<div className="demo-success" role="status"><span aria-hidden="true">✓</span><h3>Thank you.</h3><p>{message}</p><p className="request-reference">Reference: {reference}</p><small>This is an access enquiry. No payment has been taken.</small></div>:<form onSubmit={submit}><h3>Get Dhanjiva.</h3><p>Request access and discuss the right setup for your hospital.</p><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Work email<input name="email" autoComplete="email" type="email" required maxLength={254}/></label></div><label>Hospital or organisation<input name="hospital" autoComplete="organization" required minLength={2} maxLength={160}/></label><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to have these details stored to handle my access request.</span></label><button type="submit" disabled={pending} className="form-submit">{pending?'Saving request…':'Request access'}<span aria-hidden="true">↗</span></button>{message&&<p className="form-error" role="alert">{message}</p>}<small className="privacy-note">Please share business contact details only. No patient information.</small></form>}</div>
}
